# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '_radiobuttonForm.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(534, 374)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lblUlke = QtWidgets.QLabel(self.centralwidget)
        self.lblUlke.setGeometry(QtCore.QRect(38, 260, 192, 29))
        self.lblUlke.setText("")
        self.lblUlke.setObjectName("lblUlke")
        self.lblEgitim = QtWidgets.QLabel(self.centralwidget)
        self.lblEgitim.setGeometry(QtCore.QRect(286, 257, 215, 32))
        self.lblEgitim.setText("")
        self.lblEgitim.setObjectName("lblEgitim")
        self.btnUlke = QtWidgets.QPushButton(self.centralwidget)
        self.btnUlke.setGeometry(QtCore.QRect(56, 217, 112, 29))
        self.btnUlke.setObjectName("btnUlke")
        self.btnDers = QtWidgets.QPushButton(self.centralwidget)
        self.btnDers.setGeometry(QtCore.QRect(302, 215, 113, 30))
        self.btnDers.setObjectName("btnDers")
        self.groupBoxUlke = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBoxUlke.setGeometry(QtCore.QRect(38, 6, 171, 174))
        self.groupBoxUlke.setObjectName("groupBoxUlke")
        self.formLayoutWidget_2 = QtWidgets.QWidget(self.groupBoxUlke)
        self.formLayoutWidget_2.setGeometry(QtCore.QRect(21, 37, 125, 109))
        self.formLayoutWidget_2.setObjectName("formLayoutWidget_2")
        self.formLayoutUlke = QtWidgets.QFormLayout(self.formLayoutWidget_2)
        self.formLayoutUlke.setContentsMargins(0, 0, 0, 0)
        self.formLayoutUlke.setObjectName("formLayoutUlke")
        self.radioTurkiye = QtWidgets.QRadioButton(self.formLayoutWidget_2)
        self.radioTurkiye.setObjectName("radioTurkiye")
        self.formLayoutUlke.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.radioTurkiye)
        self.radioAzerbaycan = QtWidgets.QRadioButton(self.formLayoutWidget_2)
        self.radioAzerbaycan.setObjectName("radioAzerbaycan")
        self.formLayoutUlke.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.radioAzerbaycan)
        self.radioAlmanya = QtWidgets.QRadioButton(self.formLayoutWidget_2)
        self.radioAlmanya.setObjectName("radioAlmanya")
        self.formLayoutUlke.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.radioAlmanya)
        self.radioYunanistan = QtWidgets.QRadioButton(self.formLayoutWidget_2)
        self.radioYunanistan.setObjectName("radioYunanistan")
        self.formLayoutUlke.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.radioYunanistan)
        self.groupBoxEgitim = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBoxEgitim.setGeometry(QtCore.QRect(274, 10, 177, 173))
        self.groupBoxEgitim.setObjectName("groupBoxEgitim")
        self.formLayoutWidget = QtWidgets.QWidget(self.groupBoxEgitim)
        self.formLayoutWidget.setGeometry(QtCore.QRect(21, 35, 129, 108))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayoutDers = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayoutDers.setContentsMargins(0, 0, 0, 0)
        self.formLayoutDers.setObjectName("formLayoutDers")
        self.radioLise = QtWidgets.QRadioButton(self.formLayoutWidget)
        self.radioLise.setObjectName("radioLise")
        self.formLayoutDers.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.radioLise)
        self.radioyuksekLisans = QtWidgets.QRadioButton(self.formLayoutWidget)
        self.radioyuksekLisans.setObjectName("radioyuksekLisans")
        self.formLayoutDers.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.radioyuksekLisans)
        self.radioIlkokul = QtWidgets.QRadioButton(self.formLayoutWidget)
        self.radioIlkokul.setObjectName("radioIlkokul")
        self.formLayoutDers.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.radioIlkokul)
        self.radioUniversite = QtWidgets.QRadioButton(self.formLayoutWidget)
        self.radioUniversite.setObjectName("radioUniversite")
        self.formLayoutDers.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.radioUniversite)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 534, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btnUlke.setText(_translate("MainWindow", "Ülke Seçimi"))
        self.btnDers.setText(_translate("MainWindow", "Ders Seçimi"))
        self.groupBoxUlke.setTitle(_translate("MainWindow", "Ülkeler"))
        self.radioTurkiye.setText(_translate("MainWindow", "Türkiye"))
        self.radioAzerbaycan.setText(_translate("MainWindow", "Azerbaycan"))
        self.radioAlmanya.setText(_translate("MainWindow", "Almanya"))
        self.radioYunanistan.setText(_translate("MainWindow", "Yunanistan"))
        self.groupBoxEgitim.setTitle(_translate("MainWindow", "Eğitim"))
        self.radioLise.setText(_translate("MainWindow", "Lise"))
        self.radioyuksekLisans.setText(_translate("MainWindow", "Yüksek Lisans"))
        self.radioIlkokul.setText(_translate("MainWindow", "İlkokul"))
        self.radioUniversite.setText(_translate("MainWindow", "Üniversite"))
